
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Michael McCreary - x22171363
 */
public class MoodGUI extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MoodGUI
     */
    private UserGUI userGUI;
    private static final String FILE_NAME = "mood.txt";
    
    public MoodGUI(UserGUI userGUI){
        initComponents();
        this.userGUI = userGUI;
        moodTips.addActionListener((ActionListener) this);
        checkAndCreateFile();
    }
    
        private void checkAndCreateFile(){
        try{
            FileWriter fileWriter = new FileWriter(FILE_NAME, true);
            fileWriter.close();
        } catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Error creating the file: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        moodLevel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        unitsOfAlcohol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hoursInNature = new javax.swing.JTextField();
        moodTips = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        socialiseRegurlaly = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMainMenu.setText("Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("On a a scale of 1 to 10, Please rate your daily Mood");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Do you socialise regurlaly?");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smiley.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("How Many units of alcohol would you consume in a day");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("How many hours would you spend out in nature each day");

        moodTips.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        moodTips.setText("Generate Tips");

        jLabel10.setFont(new java.awt.Font("LiSong Pro", 1, 50)); // NOI18N
        jLabel10.setText("T.I.E Mood");

        socialiseRegurlaly.setText("Yes/No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(hoursInNature, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unitsOfAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moodLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(moodTips, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(socialiseRegurlaly, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 57, 57)
                .addComponent(jLabel4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainMenu)
                    .addComponent(jLabel10))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(unitsOfAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hoursInNature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(socialiseRegurlaly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moodLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(68, 68, 68)
                .addComponent(moodTips, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
        @Override
    public void actionPerformed(ActionEvent e){
        if(e.getSource() == moodTips){
            moodTipsButtonClick();
        }
    }
    
    
    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        if(userGUI != null){
            userGUI.setVisible(true);
            userGUI.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnMainMenuActionPerformed


private void moodTipsButtonClick(){
    try{
        // Read existing content from the file
        StringBuilder fileContent = new StringBuilder();
        try(BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME))){
            String line;
            while((line = reader.readLine()) != null) {
                fileContent.append(line).append("\n");
            }
        }

        // Append new tips to the content
        fileContent.append(generateMoodTips(
                Integer.parseInt(moodLevel.getText()),
                "Yes".equalsIgnoreCase(socialiseRegurlaly.getText()),
                Integer.parseInt(unitsOfAlcohol.getText()),
                Integer.parseInt(hoursInNature.getText())
        ));

        // Write the updated content back to the file
        try(BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_NAME))){
            writer.write(fileContent.toString());
        }

        // Display a message or perform any other necessary actions
        JOptionPane.showMessageDialog(this, generateMoodTips(
                Integer.parseInt(moodLevel.getText()),
                "Yes".equalsIgnoreCase(socialiseRegurlaly.getText()),
                Integer.parseInt(unitsOfAlcohol.getText()),
                Integer.parseInt(hoursInNature.getText())
        ));
        JOptionPane.showMessageDialog(this, "Mood tips written to the file.", "File Update", JOptionPane.INFORMATION_MESSAGE);

    } catch(IOException | NumberFormatException ex){
        JOptionPane.showMessageDialog(null, "Error reading/writing to the file: " + ex.getMessage());
    }
}

    private String generateMoodTips(int moodLevel, boolean socializeRegularly, int unitsOfAlcohol, int hoursInNature){
        StringBuilder tipsBuilder = new StringBuilder();

        // Mood Level Tips
        if(moodLevel < 5){
            tipsBuilder.append("Your mood is quite low. Consider seeking support from friends or professionals. \n");
        } else if(moodLevel < 7) {
            tipsBuilder.append("Your mood is moderate. Engage in activities that bring you joy. \n");
        } else{
            tipsBuilder.append("You are in a good mood. Keep up the positive vibes! \n");
        }

        // Socializing Tips
        if(!socializeRegularly){
            tipsBuilder.append("Socializing is important for mental well-being. Make an effort to connect with others. \n");
        } else{
            tipsBuilder.append("Great job on maintaining regular social activities! \n");
        }

        // Alcohol Tips
        if(unitsOfAlcohol >= 3){
            tipsBuilder.append("Binge drinking can negatively impact your mood. Consider cutting down on alcohol consumption." + '\n'
            + "If you need help getting your alcohol consumption under control please visit: https://www.drinkaware.ie/  \n");
        } else if(unitsOfAlcohol > 0){
            tipsBuilder.append("Your alcohol consumption is below recommended levels. Be mindful of its effects on your mood. \n");
        } else{
            tipsBuilder.append("You haven't consumed any alcohol. This is beneficial for your overall well-being. \n");
        }

        // Nature Tips
        if(hoursInNature < 2){
            tipsBuilder.append("Spending more time in nature can improve your mood and well-being. \n");
        } else if(hoursInNature >= 2 && hoursInNature < 5) {
            tipsBuilder.append("You are spending a decent amount of time in nature. Consider increasing it for additional benefits. \n");
        } else{
            tipsBuilder.append("You are getting a good dose of nature! Keep enjoying the outdoors. \n");
        }

        return tipsBuilder.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JTextField hoursInNature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField moodLevel;
    private javax.swing.JButton moodTips;
    private javax.swing.JTextField socialiseRegurlaly;
    private javax.swing.JTextField unitsOfAlcohol;
    // End of variables declaration//GEN-END:variables

}